### ISSUE TITLE
Mulching turns Grass field to Turnips

### ISSUE THREAD

**Issue by ZincStoat** [Timmeey86/FS22_ConservationAgriculture#6] opened 2023-12-24 20:17 UTC
This is an odd one. I've got three fields on the Chipping Norton map that started out as Meadow, which I've ploughed to created fields and sown with Grass. I never got into using grass rollers as it's just another implement to store, what I do is mulch after harvest regardless of the crop. I get the mulched bonus and with grass I get instant growth stage 1. This time around, on mulching the harvested field the Grass was converted to Parsnip. I disabled the ConservationAg mod and on resuming the field it's staying as Grass.

**Comment by Timmeey86** [comment] 2023-12-24 23:59
Thanks for the detailed description, I'll try to reproduce it as soon as I get a chance (will take a bit for to Christmas).

Mulching a harvested field is supposed to not trigger anything my mod does, so there's definitely an error somewhere.

**Comment by ZincStoat** [comment] 2023-12-25 00:10
Thanks! No hurry obviously, but I knew you were keen for feedback. In case it makes any difference, the mulcher is the Cultro 9 TC from the Horsch Agrovation Pack. Have a great Christmas break.

**Comment by Timmeey86** [comment] 2023-12-25 07:47
Hm, I tried the following but could not reproduce it:

1. Start a new save on Chipping Norton on easy
2. Use the direct seeder which comes with the save, and field creation turned on, to sow grass into the nearby meadow
3. Advance to november
4. Buy a Big M and mow the grass
5. Buy a Horsch Cultro 9 TC and mulch the mowed grass

Is there anything you're doing differently, or can you zip your savegame and upload it here?

**Comment by ZincStoat** [comment] 2023-12-27 20:06
I must confess I do have ~2800 mods installed, almost all activated, so the possibility of a conflict is fairly high. I'll do some testing and get back to you. I'm in the midst of holiday stuff myself, so please bear with me. ;)

**Comment by Timmeey86** [comment] 2023-12-27 20:09
@ZincStoat Take as much time as you need. Note that I just added a new release which allows turning features on or off in the game settings, so if you can still reproduce that effect with the new version it would be cool if you could turn some options off and see if you can narrow it down

**Comment by ZincStoat** [comment] 2023-12-27 20:14
@Timmeey86 I'll do my testing with the new version sure. I'll probably go with my "essential" mods first, and if it doesn't manifest with those, enable others 'til it does. I am a software developer myself, but while I'm a demon in my chosen field, with lua and game mods I can just about work out what the code's intended to do but wouldn't know where to start building one from scratch. I know a bit about testing though, so I'll keep you posted.

**Comment by Timmeey86** [comment] 2023-12-27 20:18
To be honest I changed so much in the mod you might be better off just adding it to the full list of mods and see if the issue occurs at all. If it does, you can still try with less mods afterwards.

**Comment by ZincStoat** [comment] 2023-12-27 20:20
@Timmeey86 one of those revisions eh? Well played, I'll do that, thanks.

**Comment by Timmeey86** [comment] 2023-12-27 20:27
Whoops, looks like I had an upper/lower case issue in v0.5.0.1 which would only be an issue once zipped. Release v0.5.0.2 should fix that

**Comment by Timmeey86** [comment] 2024-02-07 07:20
This should be fixed, see #21

**Closed** 2024-02-08 23:23 UTC
